/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package scalabank

import scalabank.logger.Logger

object App {
  def main(args: Array[String]): Unit = {
    val l: Logger = Logger(true)
    l.log("ciao")
    println(greeting())
  }

  def greeting(): String = "Hello, world!"
}
