/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package scalabank

import scalabank.entities.Person

object App {
  def main(args: Array[String]): Unit = {

  }

  def greeting(): String = "Hello, world!"
}
